import json
now='2026-09-26T09:00:00Z'
leads=[
 {"_id":"l1","ref":"GL-LEAD-2026-0041","company":"Adebayo & Sons Logistics","contact":"Tunde Adebayo","email":"tunde@adebayologistics.ng","phone":"08031234567","country":"Nigeria","industry":"Logistics","users":"25","currentEmail":"Gmail","services":["Microsoft 365"],"billing":"monthly","status":"new","createdAt":now,"assignedTo":"Henry Arukwe"},
 {"_id":"l2","ref":"GL-LEAD-2026-0038","company":"Kano Agro Processors","contact":"Aisha Bello","email":"aisha@kanoagro.com","phone":"08099887766","country":"Nigeria","industry":"Agriculture","users":"40","currentEmail":"cPanel webmail","services":["Microsoft 365","Hosting"],"billing":"annual","status":"assessment","createdAt":now},
 {"_id":"l3","ref":"GL-LEAD-2026-0035","company":"Lekki Dental Clinic","contact":"Dr. Chioma Okafor","email":"chioma@lekkidental.ng","phone":"08122334455","country":"Nigeria","industry":"Healthcare","users":"12","currentEmail":"Zoho","services":["Microsoft 365"],"billing":"monthly","status":"quoted","mrr":180000,"createdAt":now},
 {"_id":"l4","ref":"GL-LEAD-2026-0031","company":"Ikeja Law Chambers","contact":"Barr. Emeka Nwosu","email":"emeka@ikejalaw.com","phone":"08033445566","country":"Nigeria","industry":"Legal","users":"18","currentEmail":"Google Workspace","services":["Microsoft 365"],"billing":"annual","status":"negotiating","mrr":260000,"createdAt":now},
 {"_id":"l5","ref":"GL-LEAD-2026-0027","company":"Abuja Build Partners","contact":"Musa Ibrahim","email":"musa@abujabuild.ng","phone":"08055667788","country":"Nigeria","industry":"Construction","users":"30","currentEmail":"Gmail","services":["Microsoft 365"],"billing":"monthly","status":"won","mrr":420000,"createdAt":now}]
customers=[{"_id":"c1","company":"Abuja Build Partners","contact":"Musa Ibrahim","email":"musa@abujabuild.ng","phone":"08055667788","country":"Nigeria","industry":"Construction","tenantDomain":"abujabuild.onmicrosoft.com","adminEmail":"admin@abujabuild.ng","package":"secure","users":30,"services":["Microsoft 365"],"billingCycle":"monthly","mrr":420000,"arr":5040000,"setupFee":150000,"currency":"NGN","status":"active","healthScore":"green","startDate":now,"createdAt":now},
 {"_id":"c2","company":"Surulere Pharmacy Group","contact":"Ngozi Eze","email":"ngozi@surulerepharm.ng","phone":"08011223344","country":"Nigeria","industry":"Healthcare","tenantDomain":"surulerepharm.onmicrosoft.com","adminEmail":"admin@surulerepharm.ng","package":"starter","users":8,"services":["Microsoft 365"],"billingCycle":"annual","mrr":95000,"arr":1140000,"setupFee":50000,"currency":"NGN","status":"active","healthScore":"amber","startDate":now,"createdAt":now}]
transfers=[{"_id":"t1","ref":"GL-TR-2026-0012","company":"Kano Agro Processors","contact":"Aisha Bello","email":"aisha@kanoagro.com","phone":"08099887766","currentProvider":"cPanel webmail","users":"40","status":"new","createdAt":now}]
users=[{"_id":"u1","name":"Adeniyi Olayemi","email":"adeniyi.olayemi@golivecompany.com","role":"admin","active":True,"createdAt":now},
 {"_id":"u2","name":"Henry Arukwe","email":"henry.arukwe@golivecompany.com","role":"sales","active":True,"createdAt":now},
 {"_id":"u3","name":"Operations Coordinator","email":"operations@golivecompany.com","role":"operations","active":True,"createdAt":now}]
MOCKS={'/api/leads':{"success":True,"leads":leads},'/api/customers':{"success":True,"customers":customers},'/api/transfers':{"success":True,"transfers":transfers},'/api/users':{"success":True,"users":users},'/api/notifications':{"success":True,"notifications":[]}}
